version: "3.9"

services:
  mooshak:
    image: mooshak:latest
    container_name: mooshak
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - ${MOOSHAK_PORT}:80
