version: "3.9"

services:
  mooshak:
    image: mooshak:latest
    container_name: mooshak
    hostname: mooshak
    env_file:
      - .env
    build:
      dockerfile: dockerfile
      context: .
    restart: unless-stopped
    ports:
      - ${mooshak_port}:80
    volumes:
      - mooshak:/home/mooshak/data
      - apache2:/etc/apache2

volumes:
  mooshak: {}
  apache2: {}
